/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package persejava;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author HP15DA0023LA
 */
public class frmMain extends javax.swing.JFrame {
FondoPanel fondo = new FondoPanel();
ArrayList<Datos> datos = new ArrayList<Datos>();
ArrayList<Datos> datosOR = new ArrayList<Datos>();
Double pesos[] = new Double[3];
Double pesosOR[] = new Double[3];
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        this.setContentPane(fondo);
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        this.setTitle("Persoptimus Prime");
        ButtonAND.setEnabled(false);
        ButtonOR.setEnabled(false);
        TFvalor1.setEnabled(false);
        TFvalor2.setEnabled(false);
        TFrespuesta.setEnabled(false);
        TAaprendizaje.setEnabled(false);
        TAaprendizaje.setText("");
        jPeso1.setEnabled(false);
        jPeso2.setEnabled(false);
        jPeso3.setEnabled(false);
        TFvalor1.setText("");
        TFvalor2.setText("");
        this.agregar();
    }
    public void agregar(){
        // para el And
        Datos valor = new Datos();
        Datos valor1 = new Datos();
        Datos valor2 = new Datos();
        Datos valor3 = new Datos();
        //
        valor.setValores(1, 0);
        valor.setValores(1, 1);
        valor.setValores(1, 2);
        this.datos.add(valor);
        valor1.setValores(1, 0);
        valor1.setValores(0, 1);
        valor1.setValores(0, 2);
        this.datos.add(valor1);
        valor2.setValores(0, 0);
        valor2.setValores(1, 1);
        valor2.setValores(0, 2);
        this.datos.add(valor2);
        valor3.setValores(0, 0);
        valor3.setValores(0, 1);
        valor3.setValores(0, 2);
        this.datos.add(valor3);
        // 
        for(int i=0; i<3;i++){
            Double numero = ((Math.random()*1.0-(-1.0)));
            pesos[i]=numero;
        }
        
        // ################ Para el or ################
        Datos valorOr = new Datos();
        Datos valorOr1 = new Datos();
        Datos valorOr2 = new Datos();
        Datos valorOr3 = new Datos();
        //
        valorOr.setValores(1, 0);
        valorOr.setValores(1, 1);
        valorOr.setValores(1, 2);
        this.datosOR.add(valorOr);
        valorOr1.setValores(1, 0);
        valorOr1.setValores(0, 1);
        valorOr1.setValores(1, 2);
        this.datosOR.add(valorOr1);
        valorOr2.setValores(0, 0);
        valorOr2.setValores(1, 1);
        valorOr2.setValores(1, 2);
        this.datosOR.add(valorOr2);
        valorOr3.setValores(0, 0);
        valorOr3.setValores(0, 1);
        valorOr3.setValores(0, 2);
        this.datosOR.add(valorOr3);
        // 
        for(int i=0; i<3;i++){
            Double numero = ((Math.random()*1.0-(-1.0)));
            pesosOR[i]=numero;
        }
    }
    private static class FondoPanel extends JPanel{
        private Image imagen; 
        public FondoPanel() {
            
        }
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage(); //To change body of generated methods, choose Tools | Templates.
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonAprender = new javax.swing.JButton();
        TFvalor1 = new javax.swing.JTextField();
        TFvalor2 = new javax.swing.JTextField();
        ButtonAND = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAaprendizaje = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TFrespuesta = new javax.swing.JTextField();
        ButtonOR = new javax.swing.JButton();
        jPeso1 = new javax.swing.JTextField();
        jPeso2 = new javax.swing.JTextField();
        jPeso3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonAprender.setText("Aprender");
        ButtonAprender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAprenderActionPerformed(evt);
            }
        });

        ButtonAND.setText("AND");
        ButtonAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonANDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valor 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor 2");

        TAaprendizaje.setColumns(20);
        TAaprendizaje.setRows(5);
        jScrollPane1.setViewportView(TAaprendizaje);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Respuesta");

        ButtonOR.setText("OR");
        ButtonOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonORActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peso 1");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Peso 2");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peso 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ButtonAprender, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TFvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(TFvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ButtonAND, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TFrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPeso3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAprender)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAND)
                    .addComponent(ButtonOR)
                    .addComponent(jPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPeso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonANDActionPerformed
        if((!this.TFvalor1.getText().equals(""))&&(!this.TFvalor2.getText().equals(""))){
            Double result= Double.parseDouble(this.TFvalor1.getText())*pesos[0] + Double.parseDouble(this.TFvalor2.getText())*pesos[1] + pesos[2];
            if(result>0){
                this.TFrespuesta.setText("1");
            }else{
                 this.TFrespuesta.setText("0");
            }
            this.jPeso1.setText(pesos[0].toString());
            this.jPeso2.setText(pesos[1].toString());
            this.jPeso3.setText(pesos[2].toString());
        }
    }//GEN-LAST:event_ButtonANDActionPerformed

    private void ButtonAprenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAprenderActionPerformed
        ButtonAND.setEnabled(true);
        ButtonOR.setEnabled(true);
        TFvalor1.setEnabled(true);
        TFvalor2.setEnabled(true);
        TFrespuesta.setEnabled(true);
        TAaprendizaje.setEnabled(true);
        this.jPeso1.setEnabled(true);
        this.jPeso2.setEnabled(true);
        this.jPeso3.setEnabled(true);
        ButtonAprender.setEnabled(false);
        this.TAaprendizaje.setText("####### Aprendizaje AND ####### \n\n");
        this.Aprender();
        this.TAaprendizaje.setText(TAaprendizaje.getText()+"\n\n####### Aprendizaje OR  ####### \n\n");
        this.AprenderOR();
        JOptionPane.showMessageDialog(null, "¡He Aprendido!");
    }//GEN-LAST:event_ButtonAprenderActionPerformed

    private void ButtonORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonORActionPerformed
        if((!this.TFvalor1.getText().equals(""))&&(!this.TFvalor2.getText().equals(""))){
            Double result= Double.parseDouble(this.TFvalor1.getText())*pesosOR[0] + Double.parseDouble(this.TFvalor2.getText())*pesosOR[1] + pesosOR[2];
            if(result>0){
                this.TFrespuesta.setText("1");
            }else{
                 this.TFrespuesta.setText("0");
            }
            this.jPeso1.setText(pesosOR[0].toString());
            this.jPeso2.setText(pesosOR[1].toString());
            this.jPeso3.setText(pesosOR[2].toString());
        }
        
    }//GEN-LAST:event_ButtonORActionPerformed
    
    public void Aprender(){
        
        boolean aprendizaje = true;
        int salidaInt;
        while(aprendizaje){
            aprendizaje = false;
                for (int i = 0; i < 4; i++){
                    Integer esteDato[]  = datos.get(i).getValores();
                    Double salidaDoub=(esteDato[0]*pesos[0])+(esteDato[1]*pesos[1])+pesos[2];
                    if(salidaDoub>0){
                        salidaInt=1;
                    }
                    else{
                        salidaInt=0;
                    }
                    if(salidaInt!=esteDato[2]){
                        
                        pesos[0]=((Math.random()*1.0-(-1.0))) - ((Math.random()*1.0-(-1.0)));
                        pesos[1]=((Math.random()*1.0-(-1.0))) - ((Math.random()*1.0-(-1.0)));
                        pesos[2]=((Math.random()*1.0-(-1.0))) - ((Math.random()*1.0-(-1.0)));
                        this.TAaprendizaje.setText(TAaprendizaje.getText()+pesos[0].toString()+" # "+pesos[1].toString()+" # "+pesos[2].toString()+"\n");
                        aprendizaje=true;
                    }
                }
        }
    }
    
    public void AprenderOR(){
        
        boolean aprendizaje = true;
        int salidaInt;
        while(aprendizaje){
            aprendizaje = false;
                for (int i = 0; i < 4; i++){
                    Integer esteDato[]  = datosOR.get(i).getValores();
                    Double salidaDoub=(esteDato[0]*pesosOR[0])+(esteDato[1]*pesosOR[1])+pesosOR[2];
                    if(salidaDoub>0){
                        salidaInt=1;
                    }
                    else{
                        salidaInt=0;
                    }
                    if(salidaInt!=esteDato[2]){
                        
                        pesosOR[0]=((Math.random()*1.0-(-1.0))) - ((Math.random()*1.0-(-1.0)));
                        pesosOR[1]=((Math.random()*1.0-(-1.0))) - ((Math.random()*1.0-(-1.0)));
                        pesosOR[2]=((Math.random()*1.0-(-1.0))) - ((Math.random()*1.0-(-1.0)));
                        this.TAaprendizaje.setText(TAaprendizaje.getText()+pesosOR[0].toString()+" # "+pesosOR[1].toString()+" # "+pesosOR[2].toString()+"\n");
                        aprendizaje=true;
                    }
                }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAND;
    private javax.swing.JButton ButtonAprender;
    private javax.swing.JButton ButtonOR;
    private javax.swing.JTextArea TAaprendizaje;
    private javax.swing.JTextField TFrespuesta;
    private javax.swing.JTextField TFvalor1;
    private javax.swing.JTextField TFvalor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jPeso1;
    private javax.swing.JTextField jPeso2;
    private javax.swing.JTextField jPeso3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
